#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PurolatorReporting")]
	public partial class PurolatorReportingSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblPI_ApplicationUserRole(tblPI_ApplicationUserRole instance);
    partial void UpdatetblPI_ApplicationUserRole(tblPI_ApplicationUserRole instance);
    partial void DeletetblPI_ApplicationUserRole(tblPI_ApplicationUserRole instance);
    partial void InserttblPI_ApplicationUser(tblPI_ApplicationUser instance);
    partial void UpdatetblPI_ApplicationUser(tblPI_ApplicationUser instance);
    partial void DeletetblPI_ApplicationUser(tblPI_ApplicationUser instance);
    partial void InserttblPI_ApplicationRole(tblPI_ApplicationRole instance);
    partial void UpdatetblPI_ApplicationRole(tblPI_ApplicationRole instance);
    partial void DeletetblPI_ApplicationRole(tblPI_ApplicationRole instance);
    partial void InserttblEmployee(tblEmployee instance);
    partial void UpdatetblEmployee(tblEmployee instance);
    partial void DeletetblEmployee(tblEmployee instance);
    partial void InserttblPI_Application(tblPI_Application instance);
    partial void UpdatetblPI_Application(tblPI_Application instance);
    partial void DeletetblPI_Application(tblPI_Application instance);
    partial void InserttblPI_ApplicationDistrictRestriction(tblPI_ApplicationDistrictRestriction instance);
    partial void UpdatetblPI_ApplicationDistrictRestriction(tblPI_ApplicationDistrictRestriction instance);
    partial void DeletetblPI_ApplicationDistrictRestriction(tblPI_ApplicationDistrictRestriction instance);
    #endregion
		
		public PurolatorReportingSQLDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PurolatorReportingConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PurolatorReportingSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PurolatorReportingSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PurolatorReportingSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PurolatorReportingSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblPI_ApplicationUserRole> tblPI_ApplicationUserRoles
		{
			get
			{
				return this.GetTable<tblPI_ApplicationUserRole>();
			}
		}
		
		public System.Data.Linq.Table<tblPI_ApplicationUser> tblPI_ApplicationUsers
		{
			get
			{
				return this.GetTable<tblPI_ApplicationUser>();
			}
		}
		
		public System.Data.Linq.Table<vw_PI_ApplicationUser> vw_PI_ApplicationUsers
		{
			get
			{
				return this.GetTable<vw_PI_ApplicationUser>();
			}
		}
		
		public System.Data.Linq.Table<tblPI_ApplicationRole> tblPI_ApplicationRoles
		{
			get
			{
				return this.GetTable<tblPI_ApplicationRole>();
			}
		}
		
		public System.Data.Linq.Table<tblEmployee> tblEmployees
		{
			get
			{
				return this.GetTable<tblEmployee>();
			}
		}
		
		public System.Data.Linq.Table<tblPI_Application> tblPI_Applications
		{
			get
			{
				return this.GetTable<tblPI_Application>();
			}
		}
		
		public System.Data.Linq.Table<tblPI_ApplicationDistrictRestriction> tblPI_ApplicationDistrictRestrictions
		{
			get
			{
				return this.GetTable<tblPI_ApplicationDistrictRestriction>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPI_ApplicationUserRole")]
	public partial class tblPI_ApplicationUserRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPI_ApplicationUserRole;
		
		private int _idPI_ApplicationUser;
		
		private int _idPI_ApplicationRole;
		
		private string _UpdatedBy;
		
		private System.DateTime _UpdatedOn;
		
		private EntityRef<tblPI_ApplicationUser> _tblPI_ApplicationUser;
		
		private EntityRef<tblPI_ApplicationRole> _tblPI_ApplicationRole;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPI_ApplicationUserRoleChanging(int value);
    partial void OnidPI_ApplicationUserRoleChanged();
    partial void OnidPI_ApplicationUserChanging(int value);
    partial void OnidPI_ApplicationUserChanged();
    partial void OnidPI_ApplicationRoleChanging(int value);
    partial void OnidPI_ApplicationRoleChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedOnChanging(System.DateTime value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public tblPI_ApplicationUserRole()
		{
			this._tblPI_ApplicationUser = default(EntityRef<tblPI_ApplicationUser>);
			this._tblPI_ApplicationRole = default(EntityRef<tblPI_ApplicationRole>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_ApplicationUserRole", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPI_ApplicationUserRole
		{
			get
			{
				return this._idPI_ApplicationUserRole;
			}
			set
			{
				if ((this._idPI_ApplicationUserRole != value))
				{
					this.OnidPI_ApplicationUserRoleChanging(value);
					this.SendPropertyChanging();
					this._idPI_ApplicationUserRole = value;
					this.SendPropertyChanged("idPI_ApplicationUserRole");
					this.OnidPI_ApplicationUserRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_ApplicationUser", DbType="Int NOT NULL")]
		public int idPI_ApplicationUser
		{
			get
			{
				return this._idPI_ApplicationUser;
			}
			set
			{
				if ((this._idPI_ApplicationUser != value))
				{
					if (this._tblPI_ApplicationUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPI_ApplicationUserChanging(value);
					this.SendPropertyChanging();
					this._idPI_ApplicationUser = value;
					this.SendPropertyChanged("idPI_ApplicationUser");
					this.OnidPI_ApplicationUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_ApplicationRole", DbType="Int NOT NULL")]
		public int idPI_ApplicationRole
		{
			get
			{
				return this._idPI_ApplicationRole;
			}
			set
			{
				if ((this._idPI_ApplicationRole != value))
				{
					if (this._tblPI_ApplicationRole.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPI_ApplicationRoleChanging(value);
					this.SendPropertyChanging();
					this._idPI_ApplicationRole = value;
					this.SendPropertyChanged("idPI_ApplicationRole");
					this.OnidPI_ApplicationRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPI_ApplicationUser_tblPI_ApplicationUserRole", Storage="_tblPI_ApplicationUser", ThisKey="idPI_ApplicationUser", OtherKey="idPI_ApplicationUser", IsForeignKey=true)]
		public tblPI_ApplicationUser tblPI_ApplicationUser
		{
			get
			{
				return this._tblPI_ApplicationUser.Entity;
			}
			set
			{
				tblPI_ApplicationUser previousValue = this._tblPI_ApplicationUser.Entity;
				if (((previousValue != value) 
							|| (this._tblPI_ApplicationUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPI_ApplicationUser.Entity = null;
						previousValue.tblPI_ApplicationUserRoles.Remove(this);
					}
					this._tblPI_ApplicationUser.Entity = value;
					if ((value != null))
					{
						value.tblPI_ApplicationUserRoles.Add(this);
						this._idPI_ApplicationUser = value.idPI_ApplicationUser;
					}
					else
					{
						this._idPI_ApplicationUser = default(int);
					}
					this.SendPropertyChanged("tblPI_ApplicationUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPI_ApplicationRole_tblPI_ApplicationUserRole", Storage="_tblPI_ApplicationRole", ThisKey="idPI_ApplicationRole", OtherKey="idPI_ApplicationRole", IsForeignKey=true)]
		public tblPI_ApplicationRole tblPI_ApplicationRole
		{
			get
			{
				return this._tblPI_ApplicationRole.Entity;
			}
			set
			{
				tblPI_ApplicationRole previousValue = this._tblPI_ApplicationRole.Entity;
				if (((previousValue != value) 
							|| (this._tblPI_ApplicationRole.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPI_ApplicationRole.Entity = null;
						previousValue.tblPI_ApplicationUserRoles.Remove(this);
					}
					this._tblPI_ApplicationRole.Entity = value;
					if ((value != null))
					{
						value.tblPI_ApplicationUserRoles.Add(this);
						this._idPI_ApplicationRole = value.idPI_ApplicationRole;
					}
					else
					{
						this._idPI_ApplicationRole = default(int);
					}
					this.SendPropertyChanged("tblPI_ApplicationRole");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPI_ApplicationUser")]
	public partial class tblPI_ApplicationUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPI_ApplicationUser;
		
		private int _idPI_Application;
		
		private int _idEmployee;
		
		private string _UpdatedBy;
		
		private System.DateTime _UpdatedOn;
		
		private EntitySet<tblPI_ApplicationUserRole> _tblPI_ApplicationUserRoles;
		
		private EntityRef<tblPI_Application> _tblPI_Application;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPI_ApplicationUserChanging(int value);
    partial void OnidPI_ApplicationUserChanged();
    partial void OnidPI_ApplicationChanging(int value);
    partial void OnidPI_ApplicationChanged();
    partial void OnidEmployeeChanging(int value);
    partial void OnidEmployeeChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedOnChanging(System.DateTime value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public tblPI_ApplicationUser()
		{
			this._tblPI_ApplicationUserRoles = new EntitySet<tblPI_ApplicationUserRole>(new Action<tblPI_ApplicationUserRole>(this.attach_tblPI_ApplicationUserRoles), new Action<tblPI_ApplicationUserRole>(this.detach_tblPI_ApplicationUserRoles));
			this._tblPI_Application = default(EntityRef<tblPI_Application>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_ApplicationUser", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPI_ApplicationUser
		{
			get
			{
				return this._idPI_ApplicationUser;
			}
			set
			{
				if ((this._idPI_ApplicationUser != value))
				{
					this.OnidPI_ApplicationUserChanging(value);
					this.SendPropertyChanging();
					this._idPI_ApplicationUser = value;
					this.SendPropertyChanged("idPI_ApplicationUser");
					this.OnidPI_ApplicationUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_Application", DbType="Int NOT NULL")]
		public int idPI_Application
		{
			get
			{
				return this._idPI_Application;
			}
			set
			{
				if ((this._idPI_Application != value))
				{
					if (this._tblPI_Application.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPI_ApplicationChanging(value);
					this.SendPropertyChanging();
					this._idPI_Application = value;
					this.SendPropertyChanged("idPI_Application");
					this.OnidPI_ApplicationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmployee", DbType="Int NOT NULL")]
		public int idEmployee
		{
			get
			{
				return this._idEmployee;
			}
			set
			{
				if ((this._idEmployee != value))
				{
					this.OnidEmployeeChanging(value);
					this.SendPropertyChanging();
					this._idEmployee = value;
					this.SendPropertyChanged("idEmployee");
					this.OnidEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPI_ApplicationUser_tblPI_ApplicationUserRole", Storage="_tblPI_ApplicationUserRoles", ThisKey="idPI_ApplicationUser", OtherKey="idPI_ApplicationUser")]
		public EntitySet<tblPI_ApplicationUserRole> tblPI_ApplicationUserRoles
		{
			get
			{
				return this._tblPI_ApplicationUserRoles;
			}
			set
			{
				this._tblPI_ApplicationUserRoles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPI_Application_tblPI_ApplicationUser", Storage="_tblPI_Application", ThisKey="idPI_Application", OtherKey="idPI_Application", IsForeignKey=true)]
		public tblPI_Application tblPI_Application
		{
			get
			{
				return this._tblPI_Application.Entity;
			}
			set
			{
				tblPI_Application previousValue = this._tblPI_Application.Entity;
				if (((previousValue != value) 
							|| (this._tblPI_Application.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPI_Application.Entity = null;
						previousValue.tblPI_ApplicationUsers.Remove(this);
					}
					this._tblPI_Application.Entity = value;
					if ((value != null))
					{
						value.tblPI_ApplicationUsers.Add(this);
						this._idPI_Application = value.idPI_Application;
					}
					else
					{
						this._idPI_Application = default(int);
					}
					this.SendPropertyChanged("tblPI_Application");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPI_ApplicationUserRoles(tblPI_ApplicationUserRole entity)
		{
			this.SendPropertyChanging();
			entity.tblPI_ApplicationUser = this;
		}
		
		private void detach_tblPI_ApplicationUserRoles(tblPI_ApplicationUserRole entity)
		{
			this.SendPropertyChanging();
			entity.tblPI_ApplicationUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_PI_ApplicationUsers")]
	public partial class vw_PI_ApplicationUser
	{
		
		private int _idPI_Application;
		
		private string _ApplicationName;
		
		private System.Nullable<int> _idEmployee;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _UserName;
		
		private string _ActiveDirectoryName;
		
		private System.Nullable<int> _idPI_ApplicationUserRole;
		
		private System.Nullable<int> _idPI_ApplicationUser;
		
		private System.Nullable<int> _idPI_ApplicationRole;
		
		private string _RoleName;
		
		private string _RoleCode;
		
		private string _role_UpdatedBy;
		
		private System.Nullable<System.DateTime> _role_UpdatedOn;
		
		public vw_PI_ApplicationUser()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_Application", DbType="Int NOT NULL")]
		public int idPI_Application
		{
			get
			{
				return this._idPI_Application;
			}
			set
			{
				if ((this._idPI_Application != value))
				{
					this._idPI_Application = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this._ApplicationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmployee", DbType="Int")]
		public System.Nullable<int> idEmployee
		{
			get
			{
				return this._idEmployee;
			}
			set
			{
				if ((this._idEmployee != value))
				{
					this._idEmployee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(MAX)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(MAX)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(MAX)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveDirectoryName", DbType="VarChar(MAX)")]
		public string ActiveDirectoryName
		{
			get
			{
				return this._ActiveDirectoryName;
			}
			set
			{
				if ((this._ActiveDirectoryName != value))
				{
					this._ActiveDirectoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_ApplicationUserRole", DbType="Int")]
		public System.Nullable<int> idPI_ApplicationUserRole
		{
			get
			{
				return this._idPI_ApplicationUserRole;
			}
			set
			{
				if ((this._idPI_ApplicationUserRole != value))
				{
					this._idPI_ApplicationUserRole = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_ApplicationUser", DbType="Int")]
		public System.Nullable<int> idPI_ApplicationUser
		{
			get
			{
				return this._idPI_ApplicationUser;
			}
			set
			{
				if ((this._idPI_ApplicationUser != value))
				{
					this._idPI_ApplicationUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_ApplicationRole", DbType="Int")]
		public System.Nullable<int> idPI_ApplicationRole
		{
			get
			{
				return this._idPI_ApplicationRole;
			}
			set
			{
				if ((this._idPI_ApplicationRole != value))
				{
					this._idPI_ApplicationRole = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="VarChar(MAX)")]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleCode", DbType="VarChar(50)")]
		public string RoleCode
		{
			get
			{
				return this._RoleCode;
			}
			set
			{
				if ((this._RoleCode != value))
				{
					this._RoleCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_UpdatedBy", DbType="VarChar(MAX)")]
		public string role_UpdatedBy
		{
			get
			{
				return this._role_UpdatedBy;
			}
			set
			{
				if ((this._role_UpdatedBy != value))
				{
					this._role_UpdatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> role_UpdatedOn
		{
			get
			{
				return this._role_UpdatedOn;
			}
			set
			{
				if ((this._role_UpdatedOn != value))
				{
					this._role_UpdatedOn = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPI_ApplicationRoles")]
	public partial class tblPI_ApplicationRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPI_ApplicationRole;
		
		private int _idPI_Application;
		
		private string _RoleName;
		
		private string _RoleCode;
		
		private string _UpdatedBy;
		
		private System.DateTime _UpdatedOn;
		
		private EntitySet<tblPI_ApplicationUserRole> _tblPI_ApplicationUserRoles;
		
		private EntityRef<tblPI_Application> _tblPI_Application;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPI_ApplicationRoleChanging(int value);
    partial void OnidPI_ApplicationRoleChanged();
    partial void OnidPI_ApplicationChanging(int value);
    partial void OnidPI_ApplicationChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    partial void OnRoleCodeChanging(string value);
    partial void OnRoleCodeChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedOnChanging(System.DateTime value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public tblPI_ApplicationRole()
		{
			this._tblPI_ApplicationUserRoles = new EntitySet<tblPI_ApplicationUserRole>(new Action<tblPI_ApplicationUserRole>(this.attach_tblPI_ApplicationUserRoles), new Action<tblPI_ApplicationUserRole>(this.detach_tblPI_ApplicationUserRoles));
			this._tblPI_Application = default(EntityRef<tblPI_Application>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_ApplicationRole", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPI_ApplicationRole
		{
			get
			{
				return this._idPI_ApplicationRole;
			}
			set
			{
				if ((this._idPI_ApplicationRole != value))
				{
					this.OnidPI_ApplicationRoleChanging(value);
					this.SendPropertyChanging();
					this._idPI_ApplicationRole = value;
					this.SendPropertyChanged("idPI_ApplicationRole");
					this.OnidPI_ApplicationRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_Application", DbType="Int NOT NULL")]
		public int idPI_Application
		{
			get
			{
				return this._idPI_Application;
			}
			set
			{
				if ((this._idPI_Application != value))
				{
					if (this._tblPI_Application.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPI_ApplicationChanging(value);
					this.SendPropertyChanging();
					this._idPI_Application = value;
					this.SendPropertyChanged("idPI_Application");
					this.OnidPI_ApplicationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RoleCode
		{
			get
			{
				return this._RoleCode;
			}
			set
			{
				if ((this._RoleCode != value))
				{
					this.OnRoleCodeChanging(value);
					this.SendPropertyChanging();
					this._RoleCode = value;
					this.SendPropertyChanged("RoleCode");
					this.OnRoleCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPI_ApplicationRole_tblPI_ApplicationUserRole", Storage="_tblPI_ApplicationUserRoles", ThisKey="idPI_ApplicationRole", OtherKey="idPI_ApplicationRole")]
		public EntitySet<tblPI_ApplicationUserRole> tblPI_ApplicationUserRoles
		{
			get
			{
				return this._tblPI_ApplicationUserRoles;
			}
			set
			{
				this._tblPI_ApplicationUserRoles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPI_Application_tblPI_ApplicationRole", Storage="_tblPI_Application", ThisKey="idPI_Application", OtherKey="idPI_Application", IsForeignKey=true)]
		public tblPI_Application tblPI_Application
		{
			get
			{
				return this._tblPI_Application.Entity;
			}
			set
			{
				tblPI_Application previousValue = this._tblPI_Application.Entity;
				if (((previousValue != value) 
							|| (this._tblPI_Application.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPI_Application.Entity = null;
						previousValue.tblPI_ApplicationRoles.Remove(this);
					}
					this._tblPI_Application.Entity = value;
					if ((value != null))
					{
						value.tblPI_ApplicationRoles.Add(this);
						this._idPI_Application = value.idPI_Application;
					}
					else
					{
						this._idPI_Application = default(int);
					}
					this.SendPropertyChanged("tblPI_Application");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPI_ApplicationUserRoles(tblPI_ApplicationUserRole entity)
		{
			this.SendPropertyChanging();
			entity.tblPI_ApplicationRole = this;
		}
		
		private void detach_tblPI_ApplicationUserRoles(tblPI_ApplicationUserRole entity)
		{
			this.SendPropertyChanging();
			entity.tblPI_ApplicationRole = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmployee")]
	public partial class tblEmployee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEmployee;
		
		private string _PI_EmployeeId;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Title;
		
		private System.DateTime _DateHired;
		
		private string _ActiveDirectoryName;
		
		private System.Nullable<int> _idEmployeeFunction;
		
		private string _UpdatedBy;
		
		private System.DateTime _UpdatedOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmployeeChanging(int value);
    partial void OnidEmployeeChanged();
    partial void OnPI_EmployeeIdChanging(string value);
    partial void OnPI_EmployeeIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDateHiredChanging(System.DateTime value);
    partial void OnDateHiredChanged();
    partial void OnActiveDirectoryNameChanging(string value);
    partial void OnActiveDirectoryNameChanged();
    partial void OnidEmployeeFunctionChanging(System.Nullable<int> value);
    partial void OnidEmployeeFunctionChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedOnChanging(System.DateTime value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public tblEmployee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmployee", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEmployee
		{
			get
			{
				return this._idEmployee;
			}
			set
			{
				if ((this._idEmployee != value))
				{
					this.OnidEmployeeChanging(value);
					this.SendPropertyChanging();
					this._idEmployee = value;
					this.SendPropertyChanged("idEmployee");
					this.OnidEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PI_EmployeeId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PI_EmployeeId
		{
			get
			{
				return this._PI_EmployeeId;
			}
			set
			{
				if ((this._PI_EmployeeId != value))
				{
					this.OnPI_EmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._PI_EmployeeId = value;
					this.SendPropertyChanged("PI_EmployeeId");
					this.OnPI_EmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateHired", DbType="DateTime NOT NULL")]
		public System.DateTime DateHired
		{
			get
			{
				return this._DateHired;
			}
			set
			{
				if ((this._DateHired != value))
				{
					this.OnDateHiredChanging(value);
					this.SendPropertyChanging();
					this._DateHired = value;
					this.SendPropertyChanged("DateHired");
					this.OnDateHiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveDirectoryName", DbType="VarChar(MAX)")]
		public string ActiveDirectoryName
		{
			get
			{
				return this._ActiveDirectoryName;
			}
			set
			{
				if ((this._ActiveDirectoryName != value))
				{
					this.OnActiveDirectoryNameChanging(value);
					this.SendPropertyChanging();
					this._ActiveDirectoryName = value;
					this.SendPropertyChanged("ActiveDirectoryName");
					this.OnActiveDirectoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmployeeFunction", DbType="Int")]
		public System.Nullable<int> idEmployeeFunction
		{
			get
			{
				return this._idEmployeeFunction;
			}
			set
			{
				if ((this._idEmployeeFunction != value))
				{
					this.OnidEmployeeFunctionChanging(value);
					this.SendPropertyChanging();
					this._idEmployeeFunction = value;
					this.SendPropertyChanged("idEmployeeFunction");
					this.OnidEmployeeFunctionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPI_Applications")]
	public partial class tblPI_Application : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPI_Application;
		
		private string _ApplicationName;
		
		private string _UpdatedBy;
		
		private System.DateTime _UpdatedOn;
		
		private EntitySet<tblPI_ApplicationUser> _tblPI_ApplicationUsers;
		
		private EntitySet<tblPI_ApplicationRole> _tblPI_ApplicationRoles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPI_ApplicationChanging(int value);
    partial void OnidPI_ApplicationChanged();
    partial void OnApplicationNameChanging(string value);
    partial void OnApplicationNameChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedOnChanging(System.DateTime value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public tblPI_Application()
		{
			this._tblPI_ApplicationUsers = new EntitySet<tblPI_ApplicationUser>(new Action<tblPI_ApplicationUser>(this.attach_tblPI_ApplicationUsers), new Action<tblPI_ApplicationUser>(this.detach_tblPI_ApplicationUsers));
			this._tblPI_ApplicationRoles = new EntitySet<tblPI_ApplicationRole>(new Action<tblPI_ApplicationRole>(this.attach_tblPI_ApplicationRoles), new Action<tblPI_ApplicationRole>(this.detach_tblPI_ApplicationRoles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_Application", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPI_Application
		{
			get
			{
				return this._idPI_Application;
			}
			set
			{
				if ((this._idPI_Application != value))
				{
					this.OnidPI_ApplicationChanging(value);
					this.SendPropertyChanging();
					this._idPI_Application = value;
					this.SendPropertyChanged("idPI_Application");
					this.OnidPI_ApplicationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this.OnApplicationNameChanging(value);
					this.SendPropertyChanging();
					this._ApplicationName = value;
					this.SendPropertyChanged("ApplicationName");
					this.OnApplicationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPI_Application_tblPI_ApplicationUser", Storage="_tblPI_ApplicationUsers", ThisKey="idPI_Application", OtherKey="idPI_Application")]
		public EntitySet<tblPI_ApplicationUser> tblPI_ApplicationUsers
		{
			get
			{
				return this._tblPI_ApplicationUsers;
			}
			set
			{
				this._tblPI_ApplicationUsers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPI_Application_tblPI_ApplicationRole", Storage="_tblPI_ApplicationRoles", ThisKey="idPI_Application", OtherKey="idPI_Application")]
		public EntitySet<tblPI_ApplicationRole> tblPI_ApplicationRoles
		{
			get
			{
				return this._tblPI_ApplicationRoles;
			}
			set
			{
				this._tblPI_ApplicationRoles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPI_ApplicationUsers(tblPI_ApplicationUser entity)
		{
			this.SendPropertyChanging();
			entity.tblPI_Application = this;
		}
		
		private void detach_tblPI_ApplicationUsers(tblPI_ApplicationUser entity)
		{
			this.SendPropertyChanging();
			entity.tblPI_Application = null;
		}
		
		private void attach_tblPI_ApplicationRoles(tblPI_ApplicationRole entity)
		{
			this.SendPropertyChanging();
			entity.tblPI_Application = this;
		}
		
		private void detach_tblPI_ApplicationRoles(tblPI_ApplicationRole entity)
		{
			this.SendPropertyChanging();
			entity.tblPI_Application = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPI_ApplicationDistrictRestriction")]
	public partial class tblPI_ApplicationDistrictRestriction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPI_ApplicationDistrictRestriction;
		
		private int _idPI_ApplicationUser;
		
		private string _District;
		
		private string _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPI_ApplicationDistrictRestrictionChanging(int value);
    partial void OnidPI_ApplicationDistrictRestrictionChanged();
    partial void OnidPI_ApplicationUserChanging(int value);
    partial void OnidPI_ApplicationUserChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public tblPI_ApplicationDistrictRestriction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_ApplicationDistrictRestriction", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPI_ApplicationDistrictRestriction
		{
			get
			{
				return this._idPI_ApplicationDistrictRestriction;
			}
			set
			{
				if ((this._idPI_ApplicationDistrictRestriction != value))
				{
					this.OnidPI_ApplicationDistrictRestrictionChanging(value);
					this.SendPropertyChanging();
					this._idPI_ApplicationDistrictRestriction = value;
					this.SendPropertyChanged("idPI_ApplicationDistrictRestriction");
					this.OnidPI_ApplicationDistrictRestrictionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPI_ApplicationUser", DbType="Int NOT NULL")]
		public int idPI_ApplicationUser
		{
			get
			{
				return this._idPI_ApplicationUser;
			}
			set
			{
				if ((this._idPI_ApplicationUser != value))
				{
					this.OnidPI_ApplicationUserChanging(value);
					this.SendPropertyChanging();
					this._idPI_ApplicationUser = value;
					this.SendPropertyChanged("idPI_ApplicationUser");
					this.OnidPI_ApplicationUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this.OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._District = value;
					this.SendPropertyChanged("District");
					this.OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="VarChar(MAX)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
